services:
  postgres:
    container_name: api_rest
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - POSTGRES_DB=api_rest_db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - '5000:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    driver: local
